### ISSUE TITLE
Blocked by Cloudflare

### ISSUE THREAD

**Issue by PabloRNC** [valapi/node-valapi#9]
### Description

```Markdown
Hi. I have recently tested this package and I when I tried to login and get my account token Cloudflare was blocking me. I do not know either if is my problem or package one.
```

### Code

```TypeScript
import AuthClient from '@valapi/auth';

const auth = new AuthClient();

auth.login('user', 'password').then(console.log);
```

### Platform

Windows 11

### Node.js Version

20.15.0

### @valapi Version

5.0.0-beta.0

**Comment by KTNG-3** [comment]
They update the new method so it gets blocked by Cloudflare, and it should be fixed in 1-2 business days

**Comment by PabloRNC** [comment]
Great. Very appreciated

**Comment by KTNG-3** [comment]
Patched. 😊

npmjs: https://www.npmjs.com/package/@valapi/auth/v/5.0.0-beta.1
guide: https://valapi.github.io/guide/packages/auth/token/identity.html

**Comment by PabloRNC** [comment]
Great

**Comment by PabloRNC** [comment]
I have tried and I was thrown an error while executing the login function:

```
captcha_not_allowed
```

The captcha is generated correctly as I log the response and it seems to be generated without any problem.

**Comment by PabloRNC** [comment]
This is my code. I have tried it in a replit project as now I cannot test if it works locally.

```

const { Auth } = require("@valapi/auth")

const auth = new Auth();

auth.captcha().then(captcha => {
  auth.login({
    username: "user",
    password: "password",
    captcha
  }).then(token => {
    console.log(token);
  })
})```

**Comment by KTNG-3** [comment]
if you use typescript It will show that as an error
![image](https://github.com/user-attachments/assets/474bfbdb-c84d-4272-85e1-a636871215b0)

please check out the guide

1) https://valapi.github.io/guide/packages/auth/token/captcha.html
you will get `captchaResponse` variable here

2) https://valapi.github.io/guide/packages/auth/token/identity.html
and put that like this
```javascript
{
    username: "Foo".
    password: "Bar",
    captcha: captchaResponse 
}
```

**Comment by PabloRNC** [comment]
Now I have used the right captcha response and a 403 error was shown, meaning I was blocked by Cloudflare. The thing is that then I tried with a random string value and I was still blocked so I will try later.

**Comment by PabloRNC** [comment]
Now it worked thanks.

**Comment by PabloRNC** [comment]
Only one more question. Tokens expire, aren't they? 

If so how can I refresh them only when there are expired?

**Comment by KTNG-3** [comment]
This will automatically detect when Token is expired (after first authenticated)
```typescript
if (!auth.isAuthenticated) {
    await auth.reauthorize();
}
```

or just
```typescript
await auth.reauthorize();
```

https://valapi.github.io/guide/packages/auth/token/cookie.html

**Comment by PabloRNC** [comment]
All right thanks. May I ask about one unofficial endpoint which is not part of your valorant api lib but you might know?

**Comment by KTNG-3** [comment]
Unofficial

- https://github.com/Henrik-3/unofficial-valorant-api
    - https://www.npmjs.com/package/unofficial-valorant-api
- https://tracker.gg/developers

Likey Offical

- RSO
    - https://gist.github.com/Henrik-3/d6b631fb7c61821bc16b17cd347a3811
- Local Server
    - https://github.com/techchrism/valorant-api-docs/tree/trunk/docs/Other%20Local#readme
    - https://github.com/techchrism/valorant-api-docs/tree/trunk/docs/Local%20Chat#readme
- XMPP
    - https://github.com/ev3nvy/valorant-xmpp-client
    - https://github.com/ev3nvy/riot-xmpp-client-example

**Comment by PabloRNC** [comment]
The thing is that I wanted to know whether I can get a match with an user puuid that is not from my user access token

**Comment by KTNG-3** [comment]
no.

**Comment by PabloRNC** [comment]
Okey

**Comment by PabloRNC** [comment]
Hi. I am getting an auth_failure error despite my username and password are correct and I am generating a correct captcha token.
